### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by TommiRommi** [yshui/compton#1139]
Hi, I'm running picom version `vgit-b700a` on my `ThinkPad T14 Gen 1` running Arch linux kernel version `6.5.7-arch1-1` with the i3 window manager.

i3 runs picom on start up `exec --no-startup-id picom -b` and it seems to memory leak whenever it needs to visually update.

If anyone knows how to make it not memory leak, that would be very appreciated

driver info
```
Graphics:
  Device-1: Intel CometLake-U GT2 [UHD Graphics] driver: i915 v: kernel
  Device-2: Lite-On Integrated Camera driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.8 driver: X: loaded: intel
    unloaded: modesetting dri: iris gpu: i915 resolution: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: iris,swrast platforms: x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 23.2.1-arch1.2
    renderer: Mesa Intel UHD Graphics (CML GT2)
  API: Vulkan v: 1.3.264 drivers: intel surfaces: xcb,xlib
```
glxinfo -B
```
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics (CML GT2) (0x9b41)
    Version: 23.2.1
    Accelerated: yes
    Video memory: 15623MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics (CML GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.2.1-arch1.2
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.2.1-arch1.2
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.2.1-arch1.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```
picom --diagnostics
```
**Version:** vgit-b700a

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/tomas/.config/picom/picom.conf

### Drivers (inaccurate):

Intel

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics (CML GT2)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: iris
 * GL: Intel
* GL renderer: Mesa Intel(R) UHD Graphics (CML GT2)
```
my configuration file
```
# Default opacity of active windows.
active-opacity = 1.0;

# Default opacity of inactive windows.
inactive-opacity = 1.0;

# Opacity of window titlebars and borders.
frame-opacity = 1.0;

# Application-specific settings; these override the default `active-opacity`
opacity-rule = [
    "95:class_g = 'Alacritty' && focused",
    "75:class_g = 'Alacritty' && !focused"
];

# background blur
blur-background = true;
blur-method     = "gaussian";
blur-strength 	= 5;
blur-deviation 	= 8;

# corner rounding
corner-radius = 20
rounded-corners-exclude = [
    "class_g = 'i3bar'",
	"class_g = 'firefox'",
	"class_g = 'Gimp'"
];
```
